### ISSUE TITLE
[BUG:WebUI] 

### ISSUE THREAD

**Issue by OrvilleQ** [lenML/ChatTTS-Forge#105]
### 阅读 README.md 和 dependencies.md

- [X] 我已经阅读过 README.md 和 dependencies.md 文件

### 检索 issue 和 discussion

- [X] 我已经确认之前没有 issue 或 discussion 涉及此 BUG

### 检查 Forge 版本

- [X] 我已经确认问题发生在最新代码或稳定版本中

### Forge Commit 或者 Tag

f7312c11cd8e3d156dbff62367fa725d95aeaa94

### Python 版本

3.10

### PyTorch 版本

2.3.1

### 操作系统信息

Windows

### 浏览器信息

Edge

### BUG 描述

当前提交 Commit 无法用说话人种子生成语音。

### 复现步骤

WebUI 使用说话人种子进行语音生成。

### 期望结果

能生。

### 实际结果

不能。

### 错误信息

```shell
Traceback (most recent call last):
  File "D:\WTEST\ChatTTS-Forge-2\environment\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "D:\WTEST\ChatTTS-Forge-2\environment\lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\WTEST\ChatTTS-Forge-2\environment\lib\site-packages\gradio\blocks.py", line 1897, in process_api
    result = await self.call_function(
  File "D:\WTEST\ChatTTS-Forge-2\environment\lib\site-packages\gradio\blocks.py", line 1483, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\WTEST\ChatTTS-Forge-2\environment\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "D:\WTEST\ChatTTS-Forge-2\environment\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "D:\WTEST\ChatTTS-Forge-2\environment\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "D:\WTEST\ChatTTS-Forge-2\environment\lib\site-packages\gradio\utils.py", line 816, in wrapper
    response = f(*args, **kwargs)
  File "D:\WTEST\ChatTTS-Forge-2\environment\lib\site-packages\gradio\utils.py", line 816, in wrapper
    response = f(*args, **kwargs)
  File "D:\WTEST\ChatTTS-Forge-2\ChatTTS-Forge\modules\webui\webui_utils.py", line 225, in tts_generate
    spk = TTSSpeaker.from_seed(spk)
AttributeError: type object 'TTSSpeaker' has no attribute 'from_seed'
```

**Comment by zhzLuke96** [comment]
感谢反馈

fixed https://github.com/lenML/ChatTTS-Forge/commit/5c6b0983d36ea71b18e8b7360220a2665a4aac3a
