### ISSUE TITLE
[BUG:API] /prompt/refine接口异常

### ISSUE THREAD

**Issue by tuxiaoseng** [lenML/ChatTTS-Forge#116]
### 确认清单

- [X] 我已经阅读过 README.md 和 dependencies.md 文件
- [X] 我已经确认之前没有 issue 或 discussion 涉及此 BUG
- [X] 我已经确认问题发生在最新代码或稳定版本中

### Forge Commit 或者 Tag

Commits on Jul 26, 2024

### Python 版本

1

### PyTorch 版本

1

### 操作系统信息

linux

### BUG 描述

异常

### BUG 端点

1

### 复现参数

data = {
'text': 中华美食，作为世界饮食文化的瑰宝，以其丰富的种类、独特的风味和精湛的烹饪技艺而闻名于世。中国地大物博，各地区的饮食习惯和烹饪方法各具特色，形成了独树一帜的美食体系。从北方的京鲁菜、东北菜，到南方的粤菜、闽菜，无不展现出中华美食的多样性,
'prompt': [oral_2][break_3][laugh_0],
"seed": -1,
"top_P": 0.7,
"top_K": 20,
"temperature": 0.000000001,
"repetition_penalty": 1,
"max_new_token": 384,
"normalize": True,
}

### 期望结果

返回数据

### 实际结果

修改后

### 错误信息

```shell
Traceback (most recent call last):
  File "/root/autodl-tmp/tts/ChatTTS-Forge/modules/api/impl/refiner_api.py", line 33, in refiner_prompt_post
    refined_text = refiner.refine_text(
  File "/root/autodl-tmp/tts/ChatTTS-Forge/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/autodl-tmp/tts/ChatTTS-Forge/modules/refiner.py", line 26, in refine_text
    sentences = spliter.parse(text)
  File "/root/autodl-tmp/tts/ChatTTS-Forge/modules/core/tools/SentenceSplitter.py", line 35, in parse
    sentences = self.merge_text_by_threshold(sentences)
  File "/root/autodl-tmp/tts/ChatTTS-Forge/modules/core/tools/SentenceSplitter.py", line 48, in merge_text_by_threshold
    if self.len(temp_sentence) + self.len(sentence) < self.sentence_threshold:
  File "/root/autodl-tmp/tts/ChatTTS-Forge/modules/core/tools/SentenceSplitter.py", line 31, in len
    return len(self.tokenizer(text))
  File "/root/autodl-tmp/tts/ChatTTS-Forge/modules/core/tools/SentenceSplitter.py", line 10, in char_tokenizer
    return [ord(char) for char in text.split("")]
ValueError: empty separator
```

**Comment by zhzLuke96** [comment]
fixed https://github.com/lenML/ChatTTS-Forge/commit/86ae55a27dafa5e55f4243b525dabfabe0dc9550
