### ISSUE TITLE
[BUG:API] /prompt/refine接口异常

### ISSUE THREAD

**Issue by tuxiaoseng** [lenML/ChatTTS-Forge#120]
### 确认清单

- [X] 我已经阅读过 README.md 和 dependencies.md 文件
- [X] 我已经确认之前没有 issue 或 discussion 涉及此 BUG
- [X] 我已经确认问题发生在最新代码或稳定版本中

### Forge Commit 或者 Tag

e46379cdcc3b071a356fb9ad07a129d6303ddb18

### Python 版本

3.10.8

### PyTorch 版本

2.3.1

### 操作系统信息

linux

### BUG 描述

异常

### BUG 端点

/prompt/refine

### 复现参数

data = {
'text': 中华美食，作为世界饮食文化的瑰宝，以其丰富的种类、独特的风味和精湛的烹饪技艺而闻名于世。中国地大物博，各地区的饮食习惯和烹饪方法各具特色，形成了独树一帜的美食体系。从北方的京鲁菜、东北菜，到南方的粤菜、闽菜，无不展现出中华美食的多样性,
'prompt': [oral_2][break_3][laugh_0],
"seed": -1,
"top_P": 0.7,
"top_K": 20,
"temperature": 0.000000001,
"repetition_penalty": 1,
"max_new_token": 384,
"normalize": True,
}

### 期望结果

正常

### 实际结果

异常

### 错误信息

```shell
Traceback (most recent call last):
  File "/root/autodl-tmp/tts/ChatTTS-Forge/modules/api/impl/refiner_api.py", line 37, in refiner_prompt_post
    refined_text = refiner.refine_text(
  File "/root/autodl-tmp/tts/ChatTTS-Forge/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/autodl-tmp/tts/ChatTTS-Forge/modules/refiner.py", line 32, in refine_text
    refined_text = infer.refine_text(
  File "/root/autodl-tmp/tts/ChatTTS-Forge/modules/core/models/zoo/ChatTTSInfer.py", line 442, in refine_text
    return self._refine_text(
  File "/root/autodl-tmp/tts/ChatTTS-Forge/modules/core/models/zoo/ChatTTSInfer.py", line 423, in _refine_text
    return self.infer(
  File "/root/autodl-tmp/tts/ChatTTS-Forge/modules/core/models/zoo/ChatTTSInfer.py", line 104, in infer
    return next(res_gen)
  File "/root/autodl-tmp/tts/ChatTTS-Forge/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/root/autodl-tmp/tts/ChatTTS-Forge/modules/core/models/zoo/ChatTTSInfer.py", line 136, in _infer
    refined = self.instance._refine_text(
  File "/root/autodl-tmp/tts/ChatTTS-Forge/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/autodl-tmp/tts/ChatTTS-Forge/modules/repos_static/ChatTTS/ChatTTS/core.py", line 626, in _refine_text
    result = next(
  File "/root/autodl-tmp/tts/ChatTTS-Forge/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/root/autodl-tmp/tts/ChatTTS-Forge/modules/repos_static/ChatTTS/ChatTTS/model/gpt.py", line 515, in generate
    idx_next = torch.multinomial(scores, num_samples=1).to(finish.device)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
```

**Comment by zhzLuke96** [comment]
fixed https://github.com/lenML/ChatTTS-Forge/commit/77e6eebc57265a1ffeff7c28197e5511395e117e
