### ISSUE TITLE
[BUG:WebUI] 

### ISSUE THREAD

**Issue by 2open1024** [lenML/ChatTTS-Forge#127]
### 确认清单

- [X] 我已经阅读过 README.md 和 dependencies.md 文件
- [X] 我已经确认之前没有 issue 或 discussion 涉及此 BUG
- [X] 我已经确认问题发生在最新代码或稳定版本中

### Forge Commit 或者 Tag

main

### Python 版本

python: 3.10.13 |

### PyTorch 版本

torch: 2.3.1

### 操作系统信息

windows 10

### 浏览器信息

chrome

### BUG 描述

播客发送到编辑器出错，分割器发送到编辑器出错

还有这个模型modules.core.models.tts.CosyVoiceModel - INFO - No CosyVoice model found

![5](https://github.com/user-attachments/assets/0abe72f0-2bed-46f7-ba0a-8cb095ac3979)

### 复现步骤

播客发送到编辑器出错，分割器发送到编辑器出错

### 期望结果

成功

### 实际结果

报错

### 错误信息

```shell
(tts-forge) PS F:\AI\ChatTTS-Forge> python .\webui.py
2024-08-03 06:25:52,443 - modules.core.models.tts.CosyVoiceModel - INFO - No CosyVoice model found
2024-08-03 06:25:53,891 - modules.devices.devices - INFO - Using half precision: torch.float16
2024-08-03 06:25:53,891 - modules.devices.devices - INFO - Using device: cuda
2024-08-03 06:25:56,771 - modules.webui.app - INFO - WebUI module initialized
2024-08-03 06:25:56,772 - modules.webui.localization - INFO - Loaded localization file F:\AI\ChatTTS-Forge\language\zh-CN.json
F:\AI\ChatTTS-Forge\modules\webui\app.py:82: GradioUnusedKwargWarning: You have unused kwarg parameters in Blocks, please remove them: {'js': "\n    function refresh() {\n        const url = new URL(window.location);\n\n        if (url.searchParams.get('__theme') !== 'dark') {\n            url.searchParams.set('__theme', 'dark');\n            window.location.href = url.href;\n        }\n    }\n    ", 'head': '\n    <script>\n    </script>\n    '}
  with gr.Blocks(js=js_func, head=head_js, title="ChatTTS Forge WebUI") as demo:
Running on local URL:  http://0.0.0.0:7860
IMPORTANT: You are using gradio version 3.43.2, however version 4.29.0 is available, please upgrade.
--------

To create a public link, set `share=True` in `launch()`.
2024-08-03 06:26:19,331 - modules.core.models.zoo.ChatTTS - INFO - Loading ChatTTS models
2024-08-03 06:26:19,347 - modules.repos_static.ChatTTS.ChatTTS.core - INFO - try to load from local: ./models/ChatTTS
2024-08-03 06:26:19,674 - modules.repos_static.ChatTTS.ChatTTS.core - INFO - vocos loaded.
2024-08-03 06:26:19,997 - modules.repos_static.ChatTTS.ChatTTS.core - INFO - dvae loaded.
2024-08-03 06:26:22,655 - modules.repos_static.ChatTTS.ChatTTS.core - INFO - gpt loaded.
2024-08-03 06:26:22,850 - modules.repos_static.ChatTTS.ChatTTS.core - INFO - decoder loaded.
2024-08-03 06:26:22,859 - modules.repos_static.ChatTTS.ChatTTS.core - INFO - tokenizer loaded.
2024-08-03 06:26:22,859 - modules.repos_static.ChatTTS.ChatTTS.core - INFO - all models has been initialized.
2024-08-03 06:26:22,861 - modules.core.models.zoo.ChatTTS - INFO - ChatTTS models loaded
Traceback (most recent call last):
  File "D:\ProgramData\miniconda3\envs\tts-forge\lib\site-packages\gradio\queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "D:\ProgramData\miniconda3\envs\tts-forge\lib\site-packages\gradio\route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\ProgramData\miniconda3\envs\tts-forge\lib\site-packages\gradio\blocks.py", line 1440, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "D:\ProgramData\miniconda3\envs\tts-forge\lib\site-packages\gradio\blocks.py", line 1338, in postprocess_data
    assert isinstance(
AssertionError: <class 'gradio.layouts.Tabs'> Component with id 2 not a valid output component.
```

**Comment by zhzLuke96** [comment]
> `IMPORTANT: You are using gradio version 3.43.2, however version 4.29.0 is available, please upgrade.`

和 #126 一样的问题，gradio 版本太低
