### ISSUE TITLE
[Bug] chattts使用随机种子生成音色报错

### ISSUE THREAD

**Issue by zydmtaichi** [lenML/ChatTTS-Forge#153]
### 确认清单

- [X] 我已经阅读过 README.md 和 dependencies.md 文件
- [X] 我已经确认之前没有 issue 或 discussion 涉及此 BUG
- [X] 我已经确认问题发生在最新代码或稳定版本中
- [X] 我已经确认问题与 API 无关
- [X] 我已经确认问题与 WebUI 无关
- [X] 我已经确认问题与 Finetune 无关

### 你的issues

```
Traceback (most recent call last):
  File "/mnt/sdb/conda/envs/ChatTTS-Forge/lib/python3.10/site-packages/gradio/queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "/mnt/sdb/conda/envs/ChatTTS-Forge/lib/python3.10/site-packages/gradio/route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "/mnt/sdb/conda/envs/ChatTTS-Forge/lib/python3.10/site-packages/gradio/blocks.py", line 1923, in process_api
    result = await self.call_function(
  File "/mnt/sdb/conda/envs/ChatTTS-Forge/lib/python3.10/site-packages/gradio/blocks.py", line 1508, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "/mnt/sdb/conda/envs/ChatTTS-Forge/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/mnt/sdb/conda/envs/ChatTTS-Forge/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "/mnt/sdb/conda/envs/ChatTTS-Forge/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "/mnt/sdb/conda/envs/ChatTTS-Forge/lib/python3.10/site-packages/gradio/utils.py", line 818, in wrapper
    response = f(*args, **kwargs)
  File "/mnt/sdb/conda/envs/ChatTTS-Forge/lib/python3.10/site-packages/gradio/utils.py", line 818, in wrapper
    response = f(*args, **kwargs)
  File "/mnt/sdb/ChatTTS-Forge/modules/webui/tts_tab.py", line 73, in tts_generate_with_history
    audio = tts_generate(model_id=self.model_id, *args, **kwargs)
  File "/mnt/sdb/ChatTTS-Forge/modules/webui/webui_utils.py", line 248, in tts_generate
    spk = ChatTtsModel.ChatTTSModel.create_speaker_from_seed(spk)
  File "/mnt/sdb/ChatTTS-Forge/modules/core/models/tts/ChatTtsModel.py", line 24, in create_speaker_from_seed
    token = chat._sample_random_speaker().float()
AttributeError: 'Chat' object has no attribute '_sample_random_speaker'. Did you mean: 'sample_random_speaker'?
```

**Comment by zydmtaichi** [comment]
尝试修改上述报错中的`_sample_random_speaker`为`sample_random_speaker`，不能解决报错

**Comment by zydmtaichi** [comment]
@zhzLuke96 你好，请看一下上述报错情况

**Comment by zhzLuke96** [comment]
fixed https://github.com/lenML/ChatTTS-Forge/commit/c799f6c7ca97550ef737b231d9eecb493d5a4f66

**Comment by zydmtaichi** [comment]
> fixed [c799f6c](https://github.com/lenML/ChatTTS-Forge/commit/c799f6c7ca97550ef737b231d9eecb493d5a4f66)

Thanks a lot for @zhzLuke96 's help , another error for cozyvoice with same operation above is still not fixed. err info pasted below:
```
2024-09-11 15:37:17,325 - modules.core.models.tts.CosyVoiceModel - INFO - CosyVoice model loaded.
Traceback (most recent call last):
  File "/mnt/sdb/conda/envs/ChatTTS-Forge/lib/python3.10/site-packages/gradio/queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "/mnt/sdb/conda/envs/ChatTTS-Forge/lib/python3.10/site-packages/gradio/route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "/mnt/sdb/conda/envs/ChatTTS-Forge/lib/python3.10/site-packages/gradio/blocks.py", line 1923, in process_api
    result = await self.call_function(
  File "/mnt/sdb/conda/envs/ChatTTS-Forge/lib/python3.10/site-packages/gradio/blocks.py", line 1508, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "/mnt/sdb/conda/envs/ChatTTS-Forge/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/mnt/sdb/conda/envs/ChatTTS-Forge/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "/mnt/sdb/conda/envs/ChatTTS-Forge/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "/mnt/sdb/conda/envs/ChatTTS-Forge/lib/python3.10/site-packages/gradio/utils.py", line 818, in wrapper
    response = f(*args, **kwargs)
  File "/mnt/sdb/conda/envs/ChatTTS-Forge/lib/python3.10/site-packages/gradio/utils.py", line 818, in wrapper
    response = f(*args, **kwargs)
  File "/mnt/sdb/ChatTTS-Forge/modules/webui/tts_tab.py", line 73, in tts_generate_with_history
    audio = tts_generate(model_id=self.model_id, *args, **kwargs)
  File "/mnt/sdb/ChatTTS-Forge/modules/webui/webui_utils.py", line 311, in tts_generate
    sample_rate, audio_data = handler.enqueue()
  File "/mnt/sdb/ChatTTS-Forge/modules/core/handler/TTSHandler.py", line 90, in enqueue
    return self.pipeline.generate()
  File "/mnt/sdb/ChatTTS-Forge/modules/core/pipeline/pipeline.py", line 103, in generate
    synth.start_generate()
  File "/mnt/sdb/ChatTTS-Forge/modules/core/pipeline/generate/BatchSynth.py", line 48, in start_generate
    self.start_generate_sync()
  File "/mnt/sdb/ChatTTS-Forge/modules/core/pipeline/generate/BatchSynth.py", line 61, in start_generate_sync
    self.generator.generate()
  File "/mnt/sdb/ChatTTS-Forge/modules/core/pipeline/generate/BatchGenerate.py", line 51, in generate
    self.generate_batch(batch)
  File "/mnt/sdb/ChatTTS-Forge/modules/core/pipeline/generate/BatchGenerate.py", line 68, in generate_batch
    results = model.generate_batch(segments=segments, context=self.context)
  File "/mnt/sdb/ChatTTS-Forge/modules/core/models/tts/CosyVoiceModel.py", line 237, in generate_batch
    return next(self.generate_batch_stream(segments, context))
  File "/mnt/sdb/ChatTTS-Forge/modules/core/models/tts/CosyVoiceModel.py", line 296, in generate_batch_stream
    raise ValueError("spk_embedding is None")
ValueError: spk_embedding is None
```

**Comment by zydmtaichi** [comment]
> 因为 cosyvoice 没有从 seed 创建音色的功能，所以 cosyvoice 用不了 `speaker from seed`

好的，谢谢
