### ISSUE TITLE
[ISSUE] 无法使用GPU来运行

### ISSUE THREAD

**Issue by kyrosin** [lenML/ChatTTS-Forge#157]
### 确认清单

- [X] 我已经阅读过 README.md 和 dependencies.md 文件
- [X] 我已经确认之前没有 issue 或 discussion 涉及此 BUG
- [X] 我已经确认问题发生在最新代码或稳定版本中
- [X] 我已经确认问题与 API 无关
- [X] 我已经确认问题与 WebUI 无关
- [x] 我已经确认问题与 Finetune 无关

### 你的issues

我的电脑配置：
OS : window11
cpu: ryzen 5600x
gpu: rtx3060
ram: 32GB

我已尽量跟着 https://github.com/lenML/ChatTTS-Forge/blob/main/docs/dependencies.md 所提到的去做， 可是依旧遇上一些问题。 比如说我不能直接 运行 python -m pip install -r requirements.windows.txt. 后来我发现里面写着需要透过conda 来安装某些dependencies. 尽管如此，我每次运行 python webui.py 时，依然会自动使用CPU来运行。 我不太清楚是否因为我的安装次序出错，还是说我的 pytorch 依赖 版本与系统不匹配。我都是在ChatTTS-Forge文件夹里运行 
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118 -f https://mirror.sjtu.edu.cn/pytorch-wheels/torch_stable.html

以下是我个人安装的顺序：
1. git clone https://github.com/lenML/ChatTTS-Forge.git
2. cd ChatTTS-Forge
3. 自行到 https://huggingface.co/2Noise/ChatTTS 下载模型
4. 把该模型放入 ./models 里
5. 透过 main/docs/dependencies.md 所提供的链接下载ffmpeg和rubberband并放入./ffmpeg
6. 在ChatTTS-Forge文件夹里运行 
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118 -f https://mirror.sjtu.edu.cn/pytorch-wheels/torch_stable.html
7. 不知什么原因我不能直接跑 python -m pip install -r requirements.windows.txt. 所以我把里面的这两行给删除：
NOTE: 截至2024/08/13，WeTextProcessing 安裝方法，需要在conda环境下，执行命令 conda install -c conda-forge pynini==2.1.6
NOTE: 然后再执行命令 pip install WeTextProcessing==1.0.4
顺带把 gradio 版本改成 4.44.0， gradio_client 版本改成 1.3.0
8. 删除了之后我就能正常运行 python -m pip install -r requirements.windows.txt 
9. 过后我再透过terminal运行 conda activate 
10. 运行 conda install -c conda-forge pynini==2.1.6
11. conda deactivate 
12. pip install WeTextProcessing==1.0.4
13. 以上顺序皆完成后便回到ChatTTS-Forge 运行 python webui.py
![Screenshot (44)](https://github.com/user-attachments/assets/7b008815-87be-4c44-bc48-0af7f6a27fcf)

有大佬可以帮帮小白吗， 感激不尽

**Comment by kyrosin** [comment]
run this:
pip uninstall torch torchvision torchaudio
pip cache purge
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

**Comment by zhzLuke96** [comment]
> 不知什么原因我不能直接跑 python -m pip install -r requirements.windows.txt. 所以我把里面的这两行给删除

这个应该是没用的，本来就是注释的，WeTextProcessing 是可选项，不一定需要安装，windows系统安装略微麻烦，并且也不太确定是不是能正常使用
所以注释了，注释了也就不会有任何效果，所以你其实也不用删除

> 我每次运行 python webui.py 时，依然会自动使用CPU来运行

这个肯定是 pytorch 版本的问题，cuda 不可用的话会自动切换为 cpu 运行

**Comment by kyrosin** [comment]
> 这个应该是没用的，本来就是注释的，WeTextProcessing 是可选项，不一定需要安装，windows系统安装略微麻烦，并且也不太确定是不是能正常使用 所以注释了，注释了也就不会有任何效果，所以你其实也不用删除

我也不太明白为什么注释了还是会出问题：
C:\Users\admin\ChatTTS-Forge>python -m pip install -r requirements.windows.txt
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Roaming\Python\Python310\site-packages\pip\_internal\cli\base_command.py", line 105, in _run_wrapper
    status = _inner_run()
  File "C:\Users\admin\AppData\Roaming\Python\Python310\site-packages\pip\_internal\cli\base_command.py", line 96, in _inner_run
    return self.run(options, args)
  File "C:\Users\admin\AppData\Roaming\Python\Python310\site-packages\pip\_internal\cli\req_command.py", line 67, in wrapper
    return func(self, options, args)
  File "C:\Users\admin\AppData\Roaming\Python\Python310\site-packages\pip\_internal\commands\install.py", line 343, in run
    reqs = self.get_requirements(args, options, finder, session)
  File "C:\Users\admin\AppData\Roaming\Python\Python310\site-packages\pip\_internal\cli\req_command.py", line 255, in get_requirements
    for parsed_req in parse_requirements(
  File "C:\Users\admin\AppData\Roaming\Python\Python310\site-packages\pip\_internal\req\req_file.py", line 151, in parse_requirements
    for parsed_line in parser.parse(filename, constraint):
  File "C:\Users\admin\AppData\Roaming\Python\Python310\site-packages\pip\_internal\req\req_file.py", line 332, in parse
    yield from self._parse_and_recurse(filename, constraint)
  File "C:\Users\admin\AppData\Roaming\Python\Python310\site-packages\pip\_internal\req\req_file.py", line 337, in _parse_and_recurse
    for line in self._parse_file(filename, constraint):
  File "C:\Users\admin\AppData\Roaming\Python\Python310\site-packages\pip\_internal\req\req_file.py", line 368, in _parse_file
    _, content = get_file_content(filename, self._session)
  File "C:\Users\admin\AppData\Roaming\Python\Python310\site-packages\pip\_internal\req\req_file.py", line 548, in get_file_content
    content = auto_decode(f.read())
  File "C:\Users\admin\AppData\Roaming\Python\Python310\site-packages\pip\_internal\utils\encoding.py", line 34, in auto_decode
    return data.decode(
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaa in position 435: illegal multibyte sequence

> 这个肯定是 pytorch 版本的问题，cuda 不可用的话会自动切换为 cpu 运行

现在没问题了我把torch版本都升级为最新版本后便可以识别GPU.

**Comment by zhzLuke96** [comment]
done
