### ISSUE TITLE
api 接口 报错

### ISSUE THREAD

**Issue by 40740** [lenML/ChatTTS-Forge#23]
api 接口http://localhost:8000/v1/audio/speech

 报错

`2024-06-10 08:42:17,204 - modules.generate_audio - INFO - ('spk', 'female2')
2024-06-10 08:42:17,204 - modules.generate_audio - INFO - {'text': ['string'], 'infer_seed': 42, 'temperature': 0.3, 'top_P': 0.7, 'top_K': 20, 'prompt1': '', 'prompt2': '', 'prefix': ''}
  0%|                                                                                         | 0/2048 [00:00<?, ?it/s]C:\Users\lin85\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\models\llama\modeling_llama.py:649: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:455.)
  attn_output = torch.nn.functional.scaled_dot_product_attention(
100%|████████████████████████████████████████████████████████████████████████████| 2048/2048 [00:01<00:00, 1322.41it/s]
C:\Users\lin85\AppData\Local\Programs\Python\Python310\lib\site-packages\vocos\heads.py:67: UserWarning: ComplexHalf support is experimental and many operators don't support it yet. (Triggered internally at ..\aten\src\ATen\EmptyTensor.cpp:42.)
  S = mag * (x + 1j * y)
INFO:     127.0.0.1:4774 - "POST /v1/audio/speech HTTP/1.1" 200 OK
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\lin85\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\lin85\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\lin85\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\lin85\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\lin85\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\lin85\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\lin85\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\cors.py", line 91, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "C:\Users\lin85\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\cors.py", line 146, in simple_response
    await self.app(scope, receive, send)
  File "C:\Users\lin85\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Users\lin85\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\lin85\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "C:\Users\lin85\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\lin85\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\lin85\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\Users\lin85\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 69, in app
    await response(scope, receive, send)
  File "C:\Users\lin85\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\responses.py", line 270, in __call__
    async with anyio.create_task_group() as task_group:
  File "C:\Users\lin85\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "C:\Users\lin85\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\responses.py", line 273, in wrap
    await func()
  File "C:\Users\lin85\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\responses.py", line 262, in stream_response
    async for chunk in self.body_iterator:
  File "C:\Users\lin85\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\concurrency.py", line 63, in iterate_in_threadpool
    yield await anyio.to_thread.run_sync(_next, iterator)
  File "C:\Users\lin85\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\lin85\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\lin85\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\lin85\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\concurrency.py", line 53, in _next
    return next(iterator)
TypeError: '_TemporaryFileWrapper' object is not an iterator`

**Comment by 40740** [comment]
/v1/text:synthesize 接口可以生成mp3，但是文件错误，不能播放。

**Comment by 40740** [comment]
请问一下，这个接口 http://localhost:8000/v1/tts?text=
能使用自己保存的音色pt吗？目前参数好像没有看到。

**Comment by 40740** [comment]
> 请问一下，这个接口 http://localhost:8000/v1/tts?text= 能使用自己保存的音色pt吗？目前参数好像没有看到。

明白了，用对应的spk 就可以~

**Comment by zhzLuke96** [comment]
> /v1/text:synthesize 接口可以生成mp3，但是文件错误，不能播放。

你遇到的问题我这里无法复现，请提供
1. git commit hash
2. 可复现的请求request

**Comment by jiabing1988** [comment]
请问现在能自定义音频音色进行音频的合成吗
