### ISSUE TITLE
启用降噪和启用增强还是有问题

### ISSUE THREAD

**Issue by Phrixus2023** [lenML/ChatTTS-Forge#25]
启用增强无法通过控制台下载模型，我是打开dl_enhance.py文件复制链接手动下载的，然后启用增强挺慢的，等了五到十分钟才能生成样例。
启用降噪则无法使用
Traceback (most recent call last):
  File "D:\BaiduNetdiskDownload\ChatTTS-Forge\venv\lib\site-packages\gradio\queueing.py", line 532, in process_events
    response = await route_utils.call_process_api(
  File "D:\BaiduNetdiskDownload\ChatTTS-Forge\venv\lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\BaiduNetdiskDownload\ChatTTS-Forge\venv\lib\site-packages\gradio\blocks.py", line 1923, in process_api
    result = await self.call_function(
  File "D:\BaiduNetdiskDownload\ChatTTS-Forge\venv\lib\site-packages\gradio\blocks.py", line 1509, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\BaiduNetdiskDownload\ChatTTS-Forge\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "D:\BaiduNetdiskDownload\ChatTTS-Forge\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "D:\BaiduNetdiskDownload\ChatTTS-Forge\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "D:\BaiduNetdiskDownload\ChatTTS-Forge\venv\lib\site-packages\gradio\utils.py", line 832, in wrapper
    response = f(*args, **kwargs)
  File "D:\BaiduNetdiskDownload\ChatTTS-Forge\modules\webui\webui_utils.py", line 221, in tts_generate
    audio_data, sample_rate = apply_audio_enhance(
  File "D:\BaiduNetdiskDownload\ChatTTS-Forge\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\BaiduNetdiskDownload\ChatTTS-Forge\modules\webui\webui_utils.py", line 102, in apply_audio_enhance
    tensor, sr = enhancer.denoise(tensor, sr)
  File "D:\BaiduNetdiskDownload\ChatTTS-Forge\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
TypeError: ResembleEnhance.denoise() missing 1 required positional argument: 'device'

**Comment by zhzLuke96** [comment]
fixed 07cf6c1386900999b6c9436debbfcbe59f6b692a
