### ISSUE TITLE
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

### ISSUE THREAD

**Issue by QiYusheng** [lenML/ChatTTS-Forge#26]
Traceback (most recent call last):
  File "D:\chatTTS\ChatTTS-Forge\venv\lib\site-packages\gradio\queueing.py", line 532, in process_events
    response = await route_utils.call_process_api(
  File "D:\chatTTS\ChatTTS-Forge\venv\lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\chatTTS\ChatTTS-Forge\venv\lib\site-packages\gradio\blocks.py", line 1928, in process_api
    result = await self.call_function(
  File "D:\chatTTS\ChatTTS-Forge\venv\lib\site-packages\gradio\blocks.py", line 1514, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\chatTTS\ChatTTS-Forge\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "D:\chatTTS\ChatTTS-Forge\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "D:\chatTTS\ChatTTS-Forge\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "D:\chatTTS\ChatTTS-Forge\venv\lib\site-packages\gradio\utils.py", line 832, in wrapper
    response = f(*args, **kwargs)
  File "D:\chatTTS\ChatTTS-Forge\modules\webui\webui_utils.py", line 205, in tts_generate
    sample_rate, audio_data = synthesize_audio(
  File "D:\chatTTS\ChatTTS-Forge\modules\synthesize_audio.py", line 63, in synthesize_audio
    audio_segments = synthesizer.synthesize_segments(text_segments)
  File "D:\chatTTS\ChatTTS-Forge\modules\SynthesizeSegments.py", line 219, in synthesize_segments
    self.process_voice_segments(segments, bucket, audio_segments)
  File "D:\chatTTS\ChatTTS-Forge\modules\SynthesizeSegments.py", line 179, in process_voice_segments
    audio_segment = audio_data_to_segment(audio_data, sr)
  File "D:\chatTTS\ChatTTS-Forge\modules\SynthesizeSegments.py", line 25, in audio_data_to_segment
    return AudioSegment.from_file(byte_io, format="wav")
  File "D:\chatTTS\ChatTTS-Forge\venv\lib\site-packages\pydub\audio_segment.py", line 728, in from_file
    info = mediainfo_json(orig_file, read_ahead_limit=read_ahead_limit)
  File "D:\chatTTS\ChatTTS-Forge\venv\lib\site-packages\pydub\utils.py", line 274, in mediainfo_json
    res = Popen(command, stdin=stdin_parameter, stdout=PIPE, stderr=PIPE)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1438, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

---

网页可以打开，但是终端给我的链接是0.0.0.7860这个链接无法进入网页，我用的是http://127.0.0.1:7860（sd的地址）可以访问，

**Comment by zhzLuke96** [comment]
检查运行环境是否有 ffmpeg 

ffmpeg下载地址
https://www.ffmpeg.org/download.html#build-windows

**Comment by QiYusheng** [comment]
同样是win系统，有好多版本，具体要下载那个版本呢？

**Comment by zhzLuke96** [comment]
> 同样是win系统，有好多版本，具体要下载那个版本呢？

参考这个文档
https://github.com/lenML/ChatTTS-Forge/blob/main/docs/dependencies.md#%E5%AE%89%E8%A3%85-ffmpeg
