### ISSUE TITLE
[BUG:API] ERROR:root:float() argument must be a string or a real number, not 'NoneType'

### ISSUE THREAD

**Issue by ahkimkoo** [lenML/ChatTTS-Forge#49]
### 阅读 README.md 和 dependencies.md

- [X] 我已经阅读过 README.md 和 dependencies.md 文件

### 检索 issue 和 discussion

- [X] 我已经确认之前没有 issue 或 discussion 涉及此 BUG

### 检查 Forge 版本

- [X] 我已经确认问题发生在最新代码或稳定版本中

### Forge Commit 或者 Tag

main

### Python 版本

3.10

### PyTorch 版本

2.31.

### 操作系统信息

linux

### BUG 描述

请求tts, 貌似长文本分隔有问题。

### BUG 端点

/v1/tts

### 复现参数

```bash
curl --location 'http://localhost/v1/tts?text=%E7%9C%9F%E7%9A%84%E6%98%AF%E5%BF%AB%E5%A6%82%E7%8B%97%E7%A8%B3%E5%A6%82%E7%8B%97%E3%80%82%E7%9C%9F%E7%9A%84%E6%98%AF%E5%BF%AB%E5%A6%82%E7%8B%97%E7%A8%B3%E5%A6%82%E7%8B%97%E3%80%82%E7%9C%9F%E7%9A%84%E6%98%AF%E5%BF%AB%E5%A6%82%E7%8B%97%E7%A8%B3%E5%A6%82%E7%8B%97%E3%80%82%E7%9C%9F%E7%9A%84%E6%98%AF%E5%BF%AB%E5%A6%82%E7%8B%97%E7%A8%B3%E5%A6%82%E7%8B%97%E3%80%82%E7%9C%9F%E7%9A%84%E6%98%AF%E5%BF%AB%E5%A6%82%E7%8B%97%E7%A8%B3%E5%A6%82%E7%8B%97%E3%80%82%E7%9C%9F%E7%9A%84%E6%98%AF%E5%BF%AB%E5%A6%82%E7%8B%97%E7%A8%B3%E5%A6%82%E7%8B%97%E3%80%82%E7%9C%9F%E7%9A%84%E6%98%AF%E5%BF%AB%E5%A6%82%E7%8B%97%E7%A8%B3%E5%A6%82%E7%8B%97%E3%80%82%E7%9C%9F%E7%9A%84%E6%98%AF%E5%BF%AB%E5%A6%82%E7%8B%97%E7%A8%B3%E5%A6%82%E7%8B%97%E3%80%82%E7%9C%9F%E7%9A%84%E6%98%AF%E5%BF%AB%E5%A6%82%E7%8B%97%E7%A8%B3%E5%A6%82%E7%8B%97%E3%80%82%E7%9C%9F%E7%9A%84%E6%98%AF%E5%BF%AB%E5%A6%82%E7%8B%97%E7%A8%B3%E5%A6%82%E7%8B%97%E3%80%82%E7%9C%9F%E7%9A%84%E6%98%AF%E5%BF%AB%E5%A6%82%E7%8B%97%E7%A8%B3%E5%A6%82%E7%8B%97%E3%80%82%E7%9C%9F%E7%9A%84%E6%98%AF%E5%BF%AB%E5%A6%82%E7%8B%97%E7%A8%B3%E5%A6%82%E7%8B%97%E3%80%82%E7%9C%9F%E7%9A%84%E6%98%AF%E5%BF%AB%E5%A6%82%E7%8B%97%E7%A8%B3%E5%A6%82%E7%8B%97%E3%80%82%E7%9C%9F%E7%9A%84%E6%98%AF%E5%BF%AB%E5%A6%82%E7%8B%97%E7%A8%B3%E5%A6%82%E7%8B%97%E3%80%82%E7%9C%9F%E7%9A%84%E6%98%AF%E5%BF%AB%E5%A6%82%E7%8B%97%E7%A8%B3%E5%A6%82%E7%8B%97%E3%80%82%E7%9C%9F%E7%9A%84%E6%98%AF%E5%BF%AB%E5%A6%82%E7%8B%97%E7%A8%B3%E5%A6%82%E7%8B%97%E3%80%82%E7%9C%9F%E7%9A%84%E6%98%AF%E5%BF%AB%E5%A6%82%E7%8B%97%E7%A8%B3%E5%A6%82%E7%8B%97%E3%80%82%E7%9C%9F%E7%9A%84%E6%98%AF%E5%BF%AB%E5%A6%82%E7%8B%97%E7%A8%B3%E5%A6%82%E7%8B%97%E3%80%82%E7%9C%9F%E7%9A%84%E6%98%AF%E5%BF%AB%E5%A6%82%E7%8B%97%E7%A8%B3%E5%A6%82%E7%8B%97%E3%80%82%E7%9C%9F%E7%9A%84%E6%98%AF%E5%BF%AB%E5%A6%82%E7%8B%97%E7%A8%B3%E5%A6%82%E7%8B%97%E3%80%82%E7%9C%9F%E7%9A%84%E6%98%AF%E5%BF%AB%E5%A6%82%E7%8B%97%E7%A8%B3%E5%A6%82%E7%8B%97%E3%80%82%E7%9C%9F%E7%9A%84%E6%98%AF%E5%BF%AB%E5%A6%82%E7%8B%97%E7%A8%B3%E5%A6%82%E7%8B%97%E3%80%82%E7%9C%9F%E7%9A%84%E6%98%AF%E5%BF%AB%E5%A6%82%E7%8B%97%E7%A8%B3%E5%A6%82%E7%8B%97%E3%80%82%E7%9C%9F%E7%9A%84%E6%98%AF%E5%BF%AB%E5%A6%82%E7%8B%97%E7%A8%B3%E5%A6%82%E7%8B%97%E3%80%82%E7%9C%9F%E7%9A%84%E6%98%AF%E5%BF%AB%E5%A6%82%E7%8B%97%E7%A8%B3%E5%A6%82%E7%8B%97%E3%80%82%E7%9C%9F%E7%9A%84%E6%98%AF%E5%BF%AB%E5%A6%82%E7%8B%97%E7%A8%B3%E5%A6%82%E7%8B%97%E3%80%82%E7%9C%9F%E7%9A%84%E6%98%AF%E5%BF%AB%E5%A6%82%E7%8B%97%E7%A8%B3%E5%A6%82%E7%8B%97%E3%80%82%E7%9C%9F%E7%9A%84%E6%98%AF%E5%BF%AB%E5%A6%82%E7%8B%97%E7%A8%B3%E5%A6%82%E7%8B%97%E3%80%82%E7%9C%9F%E7%9A%84%E6%98%AF%E5%BF%AB%E5%A6%82%E7%8B%97%E7%A8%B3%E5%A6%82%E7%8B%97%E3%80%82%E7%9C%9F%E7%9A%84%E6%98%AF%E5%BF%AB%E5%A6%82%E7%8B%97%E7%A8%B3%E5%A6%82%E7%8B%97%E3%80%82%E7%9C%9F%E7%9A%84%E6%98%AF%E5%BF%AB%E5%A6%82%E7%8B%97%E7%A8%B3%E5%A6%82%E7%8B%97%E3%80%82%E7%9C%9F%E7%9A%84%E6%98%AF%E5%BF%AB%E5%A6%82%E7%8B%97%E7%A8%B3%E5%A6%82%E7%8B%97%E3%80%82%E7%9C%9F%E7%9A%84%E6%98%AF%E5%BF%AB%E5%A6%82%E7%8B%97%E7%A8%B3%E5%A6%82%E7%8B%97%E3%80%82%E7%9C%9F%E7%9A%84%E6%98%AF%E5%BF%AB%E5%A6%82%E7%8B%97%E7%A8%B3%E5%A6%82%E7%8B%97%E3%80%82%E7%9C%9F%E7%9A%84%E6%98%AF%E5%BF%AB%E5%A6%82%E7%8B%97%E7%A8%B3%E5%A6%82%E7%8B%97%E3%80%82%E7%9C%9F%E7%9A%84%E6%98%AF%E5%BF%AB%E5%A6%82%E7%8B%97%E7%A8%B3%E5%A6%82%E7%8B%97%E3%80%82%E7%9C%9F%E7%9A%84%E6%98%AF%E5%BF%AB%E5%A6%82%E7%8B%97%E7%A8%B3%E5%A6%82%E7%8B%97%E3%80%82%E7%9C%9F%E7%9A%84%E6%98%AF%E5%BF%AB%E5%A6%82%E7%8B%97%E7%A8%B3%E5%A6%82%E7%8B%97%E3%80%82&spk=Bob&style=advertisement_upbeat_p&temperature=0.3&top_P=0.5&top_K=20&seed=42&format=wav&bs=8&thr=100&prompt1=null&prompt2=null&prefix=null' \
--header 'accept: */*' 
```

### 期望结果

不报错

### 实际结果

报错
```bash
ERROR:root:float() argument must be a string or a real number, not 'NoneType'
Traceback (most recent call last):
  File "/root/autodl-tmp/ChatTTS-Forge/modules/api/impl/tts_api.py", line 96, in synthesize_tts
    sample_rate, audio_data = synthesize_audio(
  File "/root/autodl-tmp/ChatTTS-Forge/modules/synthesize_audio.py", line 54, in synthesize_audio
    combined_audio = combine_audio_segments(audio_segments)
  File "/root/autodl-tmp/ChatTTS-Forge/modules/SynthesizeSegments.py", line 33, in combine_audio_segments
    combined_audio += segment
  File "/root/autodl-tmp/vms/chattts/lib/python3.10/site-packages/pydub/audio_segment.py", line 366, in __add__
    return self.apply_gain(arg)
  File "/root/autodl-tmp/vms/chattts/lib/python3.10/site-packages/pydub/audio_segment.py", line 1172, in apply_gain
    db_to_float(float(volume_change))))
TypeError: float() argument must be a string or a real number, not 'NoneType'
```

**Comment by zhzLuke96** [comment]
感谢反馈

fixed 1788318a96c014a53ee41c4db7d60fdd4b15cfca

**Comment by zhzLuke96** [comment]
顺带一提，你这个参数有点问题 `prompt1=null&prompt2=null&prefix=null`

这几个值如果不需要，就不用传或者为空 `prompt1=&prompt2=&prefix=`，不然都会当作字符串作为 prompt 可能影响质量
