### ISSUE TITLE
[BUG:API] windows11手动bulid模式下，即便ffmepg已经加到环境变量，并且手动拷贝文件到ffmpeg目录下，启动api还是提示找不到ffmpeg扩展

### ISSUE THREAD

**Issue by hotdogarea** [lenML/ChatTTS-Forge#64]
### 阅读 README.md 和 dependencies.md

- [X] 我已经阅读过 README.md 和 dependencies.md 文件

### 检索 issue 和 discussion

- [X] 我已经确认之前没有 issue 或 discussion 涉及此 BUG

### 检查 Forge 版本

- [X] 我已经确认问题发生在最新代码或稳定版本中

### 你的issues

fatal: No names found, cannot describe anything.
2024-06-22 15:47:53,492 - torio._extension.utils - DEBUG - Loading FFmpeg6
2024-06-22 15:47:53,493 - torio._extension.utils - DEBUG - Failed to load FFmpeg6 extension.
Traceback (most recent call last):
  File "C:\Users\Administrator\.conda\envs\chatForge\lib\site-packages\torio\_extension\utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "C:\Users\Administrator\.conda\envs\chatForge\lib\site-packages\torio\_extension\utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "C:\Users\Administrator\.conda\envs\chatForge\lib\site-packages\torio\_extension\utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "C:\Users\Administrator\.conda\envs\chatForge\lib\site-packages\torch\_ops.py", line 1032, in load_library
    ctypes.CDLL(path)
  File "C:\Users\Administrator\.conda\envs\chatForge\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'C:\Users\Administrator\.conda\envs\chatForge\Lib\site-packages\torio\lib\libtorio_ffmpeg6.pyd' (or one of its dependencies). Try using the full path with constructor syntax.   
2024-06-22 15:47:53,495 - torio._extension.utils - DEBUG - Loading FFmpeg5
2024-06-22 15:47:53,496 - torio._extension.utils - DEBUG - Failed to load FFmpeg5 extension.
Traceback (most recent call last):
  File "C:\Users\Administrator\.conda\envs\chatForge\lib\site-packages\torio\_extension\utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "C:\Users\Administrator\.conda\envs\chatForge\lib\site-packages\torio\_extension\utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "C:\Users\Administrator\.conda\envs\chatForge\lib\site-packages\torio\_extension\utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "C:\Users\Administrator\.conda\envs\chatForge\lib\site-packages\torch\_ops.py", line 1032, in load_library
    ctypes.CDLL(path)
  File "C:\Users\Administrator\.conda\envs\chatForge\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'C:\Users\Administrator\.conda\envs\chatForge\Lib\site-packages\torio\lib\libtorio_ffmpeg5.pyd' (or one of its dependencies). Try using the full path with constructor syntax.   
2024-06-22 15:47:53,497 - torio._extension.utils - DEBUG - Loading FFmpeg4
2024-06-22 15:47:53,498 - torio._extension.utils - DEBUG - Failed to load FFmpeg4 extension.
Traceback (most recent call last):
  File "C:\Users\Administrator\.conda\envs\chatForge\lib\site-packages\torio\_extension\utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "C:\Users\Administrator\.conda\envs\chatForge\lib\site-packages\torio\_extension\utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "C:\Users\Administrator\.conda\envs\chatForge\lib\site-packages\torio\_extension\utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "C:\Users\Administrator\.conda\envs\chatForge\lib\site-packages\torch\_ops.py", line 1032, in load_library
    ctypes.CDLL(path)
  File "C:\Users\Administrator\.conda\envs\chatForge\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'C:\Users\Administrator\.conda\envs\chatForge\Lib\site-packages\torio\lib\libtorio_ffmpeg4.pyd' (or one of its dependencies). Try using the full path with constructor syntax.   
2024-06-22 15:47:53,499 - torio._extension.utils - DEBUG - Loading FFmpeg
2024-06-22 15:47:53,500 - torio._extension.utils - DEBUG - Failed to load FFmpeg extension.
Traceback (most recent call last):
  File "C:\Users\Administrator\.conda\envs\chatForge\lib\site-packages\torio\_extension\utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "C:\Users\Administrator\.conda\envs\chatForge\lib\site-packages\torio\_extension\utils.py", line 106, in _find_versionsed_ffmpeg_extension
    raise RuntimeError(f"FFmpeg{version} extension is not available.")
RuntimeError: FFmpeg extension is not available.

**Comment by Phrixus2023** [comment]
用这个环境试试https://pan.baidu.com/s/1ZBv6rC9A2P1OwQ2VPDpdzw?pwd=8xvw

**Comment by zhzLuke96** [comment]
看起来还是ffmpeg环境配置问题

建议重新配置 ffmpeg 环境，并检查在 命令行环境 中执行 `ffmpeg -version` 是否有回应

如果还是不行，除了手动下载，并配置系统环境变量以外，还可以尝试使用 conda 来安装 ffmpeg

**Comment by hotdogarea** [comment]
命令行 conda都能正常运行



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: luke zhang ***@***.***&gt;
发送时间: 2024年6月23日 17:09
收件人: lenML/ChatTTS-Forge ***@***.***&gt;
抄送: hotdogarea ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[lenML/ChatTTS-Forge] [BUG:API] windows11手动bulid模式下，即便ffmepg已经加到环境变量，并且手动拷贝文件到ffmpeg目录下，启动api还是提示找不到ffmpeg扩展 (Issue #64)





 
看起来还是ffmpeg环境配置问题
 
建议重新配置 ffmpeg 环境，并检查在 命令行环境 中执行 ffmpeg -version 是否有回应
 
如果还是不行，除了手动下载，并配置系统环境变量以外，还可以尝试使用 conda 来安装 ffmpeg
