### ISSUE TITLE
[BUG:FT] 调节器无法使用

### ISSUE THREAD

**Issue by Phrixus2023** [lenML/ChatTTS-Forge#68]
### 阅读 README.md 和 dependencies.md

- [X] 我已经阅读过 README.md 和 dependencies.md 文件

### 检索 issue 和 discussion

- [X] 我已经确认之前没有 issue 或 discussion 涉及此 BUG

### 检查 Forge 版本

- [X] 我已经确认问题发生在最新代码或稳定版本中

### Forge Commit 或者 Tag

调节器问题

### Python 版本

3.10.11

### PyTorch 版本

torch: 2.3.1+cpu

### 操作系统信息

windows11

### BUG 描述

无法使用调节器进行生成声音，ffmpeg正常 ffmpeg: N-115838-g4e4444f97c-20240615

### 复现步骤

修改调节器参数进行音频生成。

### 期望结果

能够正常使用调节器

### 实际结果

控制台报错缺失rubberband-cli

### 错误信息

```shell
2024-06-24 14:40:58,256 - httpx - INFO - HTTP Request: GET https://api.gradio.app/gradio-messaging/en "HTTP/1.1 200 OK"
2024-06-24 14:40:59,899 - numexpr.utils - INFO - Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
2024-06-24 14:40:59,899 - numexpr.utils - INFO - NumExpr defaulting to 8 threads.
D:\BaiduNetdiskDownload\ChatTTS-Forge20240624\pythonEmbed\lib\site-packages\transformers\utils\hub.py:124: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
2024-06-24 14:41:04,535 - modules.generate_audio - INFO - LRU cache enabled with size 64
2024-06-24 14:41:04,535 - modules.devices.devices - INFO - Using full precision: torch.float32
2024-06-24 14:41:04,535 - modules.devices.devices - INFO - Using device: cpu
2024-06-24 14:41:04,540 - modules.webui.app - INFO - WebUI module initialized
2024-06-24 14:41:04,540 - modules.webui.localization - INFO - Loaded localization file D:\BaiduNetdiskDownload\ChatTTS-Forge20240624\language\zh-CN.json
2024-06-24 14:41:05,020 - httpx - INFO - HTTP Request: GET https://checkip.amazonaws.com/ "HTTP/1.1 200 "
Running on local URL:  http://0.0.0.0:7860
2024-06-24 14:41:05,540 - httpx - INFO - HTTP Request: GET https://api.gradio.app/pkg-version "HTTP/1.1 200 OK"
2024-06-24 14:41:07,210 - httpx - INFO - HTTP Request: GET http://localhost:7860/startup-events "HTTP/1.1 200 OK"
2024-06-24 14:41:09,264 - httpx - INFO - HTTP Request: HEAD http://localhost:7860/ "HTTP/1.1 200 OK"

To create a public link, set `share=True` in `launch()`.
2024-06-24 14:41:35,501 - modules.models - INFO - Loading ChatTTS models
2024-06-24 14:41:35,501 - modules.ChatTTS.ChatTTS.core - INFO - Load from local: ./models/ChatTTS
2024-06-24 14:41:35,775 - modules.ChatTTS.ChatTTS.core - INFO - vocos loaded.
2024-06-24 14:41:35,885 - modules.ChatTTS.ChatTTS.core - INFO - dvae loaded.
2024-06-24 14:41:39,120 - modules.ChatTTS.ChatTTS.core - INFO - gpt loaded.
2024-06-24 14:41:39,363 - modules.ChatTTS.ChatTTS.core - INFO - decoder loaded.
2024-06-24 14:41:39,380 - modules.ChatTTS.ChatTTS.core - INFO - tokenizer loaded.
2024-06-24 14:41:39,380 - modules.ChatTTS.ChatTTS.core - INFO - All initialized.
2024-06-24 14:41:39,383 - modules.models - INFO - ChatTTS models loaded
Traceback (most recent call last):
  File "D:\BaiduNetdiskDownload\ChatTTS-Forge20240624\pythonEmbed\lib\site-packages\pyrubberband\pyrb.py", line 74, in __rubberband
    subprocess.check_call(arguments, stdout=DEVNULL, stderr=DEVNULL)
  File "subprocess.py", line 364, in check_call
  File "subprocess.py", line 345, in call
  File "subprocess.py", line 971, in __init__
  File "subprocess.py", line 1456, in _execute_child
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\BaiduNetdiskDownload\ChatTTS-Forge20240624\pythonEmbed\lib\site-packages\gradio\queueing.py", line 532, in process_events
    response = await route_utils.call_process_api(
  File "D:\BaiduNetdiskDownload\ChatTTS-Forge20240624\pythonEmbed\lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\BaiduNetdiskDownload\ChatTTS-Forge20240624\pythonEmbed\lib\site-packages\gradio\blocks.py", line 1928, in process_api
    result = await self.call_function(
  File "D:\BaiduNetdiskDownload\ChatTTS-Forge20240624\pythonEmbed\lib\site-packages\gradio\blocks.py", line 1514, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\BaiduNetdiskDownload\ChatTTS-Forge20240624\pythonEmbed\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "D:\BaiduNetdiskDownload\ChatTTS-Forge20240624\pythonEmbed\lib\site-packages\anyio\_backends\_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
  File "D:\BaiduNetdiskDownload\ChatTTS-Forge20240624\pythonEmbed\lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "D:\BaiduNetdiskDownload\ChatTTS-Forge20240624\pythonEmbed\lib\site-packages\gradio\utils.py", line 832, in wrapper
    response = f(*args, **kwargs)
  File "D:\BaiduNetdiskDownload\ChatTTS-Forge20240624\pythonEmbed\lib\site-packages\gradio\utils.py", line 832, in wrapper
    response = f(*args, **kwargs)
  File "D:\BaiduNetdiskDownload\ChatTTS-Forge20240624\modules\webui\webui_utils.py", line 256, in tts_generate
    audio_data, sample_rate = handler.enqueue()
  File "D:\BaiduNetdiskDownload\ChatTTS-Forge20240624\modules\api\impl\handler\TTSHandler.py", line 95, in enqueue
    audio_data = apply_prosody_to_audio_data(
  File "D:\BaiduNetdiskDownload\ChatTTS-Forge20240624\modules\utils\audio.py", line 106, in apply_prosody_to_audio_data
    audio_data = pyrb.time_stretch(audio_data, sr=sr, rate=rate)
  File "D:\BaiduNetdiskDownload\ChatTTS-Forge20240624\pythonEmbed\lib\site-packages\pyrubberband\pyrb.py", line 142, in time_stretch
    return __rubberband(y, sr, **rbargs)
  File "D:\BaiduNetdiskDownload\ChatTTS-Forge20240624\pythonEmbed\lib\site-packages\pyrubberband\pyrb.py", line 84, in __rubberband
    six.raise_from(RuntimeError('Failed to execute rubberband. '
  File "<string>", line 3, in raise_from
RuntimeError: Failed to execute rubberband. Please verify that rubberband-cli is installed.
```

**Comment by zhzLuke96** [comment]
具体看这个文档安装音频后端

https://github.com/lenML/ChatTTS-Forge/blob/main/docs/dependencies.md#%E8%84%9A%E6%9C%AC%E5%AE%89%E8%A3%85
